// <auto-generated />
using LATESTReactKanBanDo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LATESTReactKanBanDo.Migrations
{
    [DbContext(typeof(KanbanDoDbContext))]
    partial class KanbanDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterKanbanDoSaitynai.Data.Entities.Column", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ViewId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ViewId");

                b.ToTable("Columns");
            });

            modelBuilder.Entity("MasterKanbanDoSaitynai.Data.Entities.TaskItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ColumnId")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ColumnId");

                b.ToTable("Tasks");
            });

            modelBuilder.Entity("MasterKanbanDoSaitynai.Data.Entities.View", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Views");
            });

            modelBuilder.Entity("MasterKanbanDoSaitynai.Data.Entities.Column", b =>
            {
                b.HasOne("MasterKanbanDoSaitynai.Data.Entities.View", "View")
                    .WithMany()
                    .HasForeignKey("ViewId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("View");
            });

            modelBuilder.Entity("MasterKanbanDoSaitynai.Data.Entities.TaskItem", b =>
            {
                b.HasOne("MasterKanbanDoSaitynai.Data.Entities.Column", "Column")
                    .WithMany()
                    .HasForeignKey("ColumnId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Column");
            });
#pragma warning restore 612, 618
        }
    }
}
